language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean update compile test package publishOnlyWhenOnMaster "project scalahost-runtime" "+ publishOnlyWhenOnMaster"
scala:
  - 2.11.0
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk8
notifications:
  email:
    - eugene.burmako@epfl.ch
    - denys.shabalin@typesafe.com
env:
  global:
   - SCALAREFLECT_MAVEN_REALM="Sonatype Nexus Repository Manager"
   - SCALAREFLECT_MAVEN_DOMAIN="oss.sonatype.org"
   - secure: "dk/Yvt4ASpraRMraeTqKAE5bAEBG7ZbmP48xAanptQBLxxlqqt4FxQq505ECjVjm9Mt8lEdknLh8uar8q5iFPX3ATWgbYPbC+lNhh22QxCMucbMKc2/F8mv5wNwZh3JMkjy+l3Nv3AAnCRW3jLxkv7ciY6JEx6Dw8BkXroVQjnE="
   - secure: "L4H8Ga1q8BCaHGN2AQ1PbAwpdeUjfYaWr35Uho95UuVha08Q6rJak3NJ1JBMh9ZjZ9BX+H6NcfX6yp263mHAf8jv1+KDcD4yDLR8oeB/os1hxN4yhonk6VFwuZKGsEgUcZEPDUwhL7NnckTADaQihBE/NKw1xdFJYaNMwp0N0kg="
